### ISSUE TITLE
Store Migration - XML Feed Question

### ISSUE THREAD

**Issue by dpanta94** [skroutz/developer.skroutz.gr#140]
Hello and thank you in advance for your time!

We are trying to migrate a client's e-shop to another platform. I would like to ask what consequences would we face if after the migration, the XML feed specifies different UniqueIds for the same products than the XML feed before the migration ?

https://developer.skroutz.gr/feedspec/#unique-id

Thank you again!

**Comment by cioannid** [comment]
Hello @dpanta94!

Thank you for reaching out.

> I would like to ask what consequences would we face if after the migration, the XML feed specifies different UniqueIds for the same products than the XML feed before the migration ?

As you've already observed on [developer notes](https://developer.skroutz.gr/feedspec/#unique-id), "The value of the field `UniqueID` must remain the same through a product's lifecycle and cannot be reused in other products.". If this field isn't preserved, the XML products with the new IDs cannot be recognized and mapped to the products we already have stored in our DB; they will be considered as new ones and they will have to be processed from scratch.

If the ID change is inevitable, the best workaround is to include (temporarily) a new field per product in the XML, namely <old_id>, which obviously contains the product ID that the shop has been sending to us so far. This way, we can update our DB safely and no information will be lost, nor extra work will be needed when the new IDs will be used.

If sending `<old_id>` is not possible either, we can attempt a best guess effort where we'll try to map the new IDs with the existent products based on other product information. However, this is not guaranteed to succeed all the times.

The worst case scenario is when no mapping is possible at all. Then, all products have to reprocessed. Depending on the XML size, this can take up to 10-15 workdays.

To be precise, all processes require some downtime, i.e. time that the shop won't be visible to Skroutz users. However, the former methods are a bit more automated, so the downtime will be shorter.

Once you're ready to deploy the store with its new platform, but **before doing so**, please send us a ticket through Merchants panel so that we achieve the best possible coordination of the migration.

At your disposal,
Skroutz engineering
