### ISSUE TITLE
XML feed specification update

### ISSUE THREAD

**Issue by LeosHumpolik** [skroutz/developer.skroutz.gr#174]
Hello, I have a question for you regarding the ideal form of the XML feed.

I looked at the specification of the XML feed at https://developer.skroutz.gr/feedspec/ and noticed a discrepancy in the description of the elements.

**Some elements have different forms on the specification page 3, depending on where they are written.**

For example, the element for "**Additional Image Link**":
- The specification page states that it should look like "additional_imageurl"
- Listed in the sample feed as "additionalimage"
- The XSD schema is then listed as "additional_image"

Another example of the "**Unique ID**" element:
- The specification lists the following 3 registration options:
<UniqueID> 32 </UniqueID> <product id = "44"> ... </product> <PRODUCTID> 232AD </PRODUCTID>
- The sample feed contains: "id"
- The XSD schema then states: "uid"

How should we base the XML file check?
Would it be possible to update the specifications or send the ideal sample feed?

Thank you very much in advance for the help and have a nice day

Leoš Humpolík

**Comment by itholoenos** [comment]
Hello @LeosHumpolik!

Thank you for reaching out to us!

We do not require a specific document template because the attributes of your XML file will be mapped to the recognized attributes described in the [feedspec](https://developer.skroutz.gr/feedspec). You can use our XML validator https://validator.skroutz.gr to check your XML file and mappings.

The provided [XSD schema](https://developer.skroutz.gr/feedspec/#xsd) is just an example, demonstrating how a mapped XML file will be validated. For example, if the attribute `uid` is mapped as the `Unique ID`, it must be a string with a maximum length of 200 characters.

However, we will update the example to match the given XSD to avoid any confusion in the future.

We remain at your disposal for any further information.
