### ISSUE TITLE
Retrieve a single order with customer's mobile number

### ISSUE THREAD

**Issue by Yiannistaos** [skroutz/developer.skroutz.gr#191]
Hi guys,

As I can see on your documentation page [here](https://developer.skroutz.gr/smart_cart/orders_api/#retrieve-a-single-order), the response of the endpoint "Retrieve a single order
" `GET /merchants/ecommerce/orders/:code`, does not include the mobile number in the `customer` object, as you can see in the screenshot below. Is it possible to retrieve also the mobile number of the customer? 

How we can contact the customer if there is a problem with his order?

<img width="981" alt="Screenshot 2022-07-26 at 00 23 31" src="https://user-images.githubusercontent.com/8467542/180877087-0676884a-b0c3-4197-955b-252692ed0bad.png">

Looking forward to your answer.
Thanks in advance.

**Comment by nikostsaganos** [comment]
Hello Yannis!

We currently don't include the customer's mobile phone in our API/Webhook payloads as you noticed. This is mostly for data privacy reasons (data minimisation), since these data can reach multiple 3rd party endpoints/servers. So, it is not planned to add the mobile phone in those payloads in the near future.

Merchants can still get this the mobile phone information in orders management in Merchants panel as of today.

Thanks a lot for reaching out!

**Comment by Yiannistaos** [comment]
@nikostsaganos thanks for letting me know. Enjoy your day!

**Comment by geokongr** [comment]
Hello,

As per documentation, currently i see support for phone and mobile with note "only available for FBM (Fulfilled By Merchant) orders or orders with invoice.": [](https://developer.skroutz.gr/smart_cart/webhook/#customer-details)

However, i notice we get phone and/or mobile via webhook only when customer chooses invoice. Shouldn't it be sending the phones for all FMB orders as well?

**Comment by fotistsisk** [comment]
Hello @geokongr,

You’re correct that, according to the documentation, phone and mobile information should be available for all FBM orders.

If there’s a specific order where you’re experiencing this issue, I recommend creating a ticket through the merchant's panel for further investigation. This will help us address any discrepancies effectively.

Best Regards,
Tsiskakis Fotis
