### ISSUE TITLE
Google analytics and marketplace revenue 

### ISSUE THREAD

**Issue by Mixfot** [skroutz/developer.skroutz.gr#240]
We have an issue with our Google analytics account. Due to we have intergrated skroutz merchants to our erp system bridge for handling orders the Google analytics count that revenue as a direct or unassigned revenue from our site which is wrong. How can we skip these data from our analytics data

**Comment by fotistsisk** [comment]
Hi [Recipient's Name],

Thank you for reaching out to us regarding the issue with your Google Analytics revenue tracking. After reviewing the situation on our end, it appears that the problem might stem from your Google Analytics configuration or setup rather than our ERP system bridge.

Unfortunately, as this seems to be outside of our scope, we’re unable to provide further assistance.

We hope this helps, and feel free to contact us if you need any further assistance with our system.

Best regards,
Tsiskakis Fotis
