### ISSUE TITLE
Not accepting access requests

### ISSUE THREAD

**Issue by loremaps** [skroutz/developer.skroutz.gr#89]
Hi,
Can you please provide some more info about not accepting access request?
Is there a timeline when access request will be open again?

**Comment by freestyl3r** [comment]
Hello from Skroutz.gr,

Further to your message, we would like to inform you that our company decided to stop providing API access to external requests, due to internal business reasons. For the time being, it is not in our plans to enable API applications.

Thank you for your understanding.
We remain at your disposal for any further information.
