### ISSUE TITLE
API Access Request

### ISSUE THREAD

**Issue by NoSGR** [skroutz/developer.skroutz.gr#99]
Hello,

I'd like to build a new application using your api for my website, is there any way to obtain access on it?

Thanks in advance

**Comment by kosdiamantis** [comment]
Hello from Skroutz.gr,

Further to your message, we would like to inform you that our company decided to stop providing API access to external requests, due to internal business reasons. For the time being, it is not in our plans to enable API applications.

Thank you for your understanding.
We remain at your disposal for any further information.
